set_property PACKAGE_PIN H4   [get_ports clk]
set_property IOSTANDARD  LVCMOS33    [get_ports clk]
set_property PACKAGE_PIN J1 [get_ports {led[0]}]
set_property IOSTANDARD  LVCMOS33    [get_ports {led[0]}]
set_property PACKAGE_PIN A13 [get_ports {led[1]}]
set_property IOSTANDARD  LVCMOS33    [get_ports {led[1]}]
set_property PACKAGE_PIN P9  [get_ports {led[2]}]
set_property IOSTANDARD  LVCMOS33    [get_ports {led[2]}]
